version: "3.7"
services:
  joynr-discovery-directory:
    image: "holomekc/joynr-discovery-directory-jee:latest"
    container_name: joynr_discovery_directory_jee
    build: .
    depends_on:
      - joynr-db
      - mqtt
    ports:
    - "8088:8080"
    - "8089:8081"
    environment:
      DB_HOST: joynr-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: joynr_discovery_directory
      MQTT_HOST: mqtt
      MQTT_PORT: 1883
  joynr-db:
    image: "postgres:9.5"
    container_name: joynr_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres_rs
      POSTGRES_DB: joynr_discovery_directory
  mqtt:
    image: "eclipse-mosquitto"
    container_name: rs_mosquitto